### ISSUE TITLE
OriDE.exe caused an Access Violation (0xc0000005)

### ISSUE THREAD

**Issue by 5ully** [c-ostic/OriBFArchipelago#10]
Most common crash currently seems to be Access Violation (0xc0000005), Ive seen this show up in the error log and output log as either just a combination of Crash! and the Violation or in some output logs a IndexOutOfRangeException: Array index is out of range. is thrown just ahead of the crash. This IndexOutOfRange might be unrelated, but im including it for the time.

Ill add 4 logs (both output and error log from both combinations)
[error_IndexOutOfRange.log](https://github.com/user-attachments/files/16806348/error_IndexOutOfRange.log)
[output_log_IndexOutOfRange.txt](https://github.com/user-attachments/files/16806349/output_log_IndexOutOfRange.txt)
[error_crash.log](https://github.com/user-attachments/files/16806366/error_crash.log)
[output_log_crash.txt](https://github.com/user-attachments/files/16806367/output_log_crash.txt)

**Comment by c-ostic** [comment]
Fixed in version 0.1.2 with changes to the message system
