### ISSUE TITLE
Test Message on Item Collection

### ISSUE THREAD

**Issue by GammaEspeon** [c-ostic/OriBFArchipelago#18]
When picking up UpperGinsoRedirectLowerExp, I got a test message instead of an actual item and location name response. The item received according to the log was an ability cell.

This was followed by a long list of item collections that were not called out at all, the log was required to know what items were being obtained, and they weren't actually being awarded in game (keystones weren't incrementing, skills were not unlocked) until reloading the game, where all of them were awarded at once when reconnecting to the host. Possibly a connection issue.

**Comment by c-ostic** [comment]
Fixed in version 0.1.2
