### ISSUE TITLE
Hard Lock (No Crash)

### ISSUE THREAD

**Issue by GammaEspeon** [c-ostic/OriBFArchipelago#20]
When picking up LostGroveLongSwim, the game completely froze. It didn't crash out so I don't have a crash report log to share.

I was streaming the run, so if it helps, this is a clip of it: https://www.twitch.tv/videos/2249970744

**Comment by c-ostic** [comment]
This is likely an issue that was fixed in a previous update. Potentially version 0.1.2-alpha where async calls to the AP server replaced sync calls. If this is not the case, then this issue can be reopened
