### ISSUE TITLE
Ginso Arena Doors Softlock

### ISSUE THREAD

**Issue by c-ostic** [c-ostic/OriBFArchipelago#9]
The doors on either side of the arena in the Ginso tree are not acting as expected

**Comment by 5ully** [comment]
Im fairly sure this happens if you don't cross over from the Spirit Well to the door before killing the mini boss. Inceracting with the door closing trigger before the fight should make the room work as intended.

**Comment by c-ostic** [comment]
Fixed in version 0.1.3
